export enum ROUTE {
  HOME = "/React-blog-app",
  NEWS = "/React-blog-app/news",
  ARTICLES = "/React-blog-app/articles",
  FAVORIRES = "/React-blog-app/favorites",
  DETAIL_ARTICLE = "/React-blog-app/article-post/:id",
  DETAIL_NEWS = "/React-blog-app/news-post/:id",
  DETAIL = "/React-blog-app/post/:id",
  // DETAIL_NEWS = "/React-blog-app/news/:id",
  AUTH = "/React-blog-app/authorization",
  REG = "/React-blog-app/registration",
  RESET_PASSWORD = "/React-blog-app/resetpass",
  SEARCH = "/React-blog-app/search",
  NOT_FOUND = "*",
}
